openapi: 3.0.2
info:
  version: v1
  title: api.getaddress.io
  description: A simple API for finding postal addresses
  termsOfService: https://getaddress.io/terms
  contact:
    name: Support
    url: https://getaddress.io
    email: support@getaddress.io
paths:
  "/find/{postcode}?{expand}":
    summary: Autocompletes lookup - returns all postcodes/house numbers
    get:
      tags:
        - Autocomplete
      operationId: AutocompletePostalAddress
      parameters:
        - examples:
            KY118NX:
              value: KY118NX
        - name: postcode
          in: path
          required: true
          schema:
            type: string
        - name: expand
          required: false
          in: path
          schema:
            type: boolean
      responses:
        "200":
          description: Returns postal addresses
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FindResponse"
              examples:
                KY118NX:
                  value:
                    postcode: KY11 8NX
                    latitude: 56.0473575
                    longitude: -3.4145963
                    addresses:
                    - formatted_address:
                      - Atag Heating Eire Ltd
                      - 1 Masterton Park
                      - South Castle Drive
                      - Dunfermline
                      - Fife
                      thoroughfare: South Castle Drive
                      building_name: Masterton Park
                      sub_building_name: Atag Heating Eire Ltd
                      sub_building_number: ''
                      building_number: '1'
                      line_1: Atag Heating Eire Ltd
                      line_2: 1 Masterton Park
                      line_3: South Castle Drive
                      line_4: ''
                      locality: ''
                      town_or_city: Dunfermline
                      county: Fife
                      district: Fife
                      country: Scotland
                    - formatted_address:
                      - Clcb Holdings Ltd
                      - 1 Masterton Park
                      - South Castle Drive
                      - Dunfermline
                      - Fife
                      thoroughfare: South Castle Drive
                      building_name: Masterton Park
                      sub_building_name: Clcb Holdings Ltd
                      sub_building_number: ''
                      building_number: '1'
                      line_1: Clcb Holdings Ltd
                      line_2: 1 Masterton Park
                      line_3: South Castle Drive
                      line_4: ''
                      locality: ''
                      town_or_city: Dunfermline
                      county: Fife
                      district: Fife
                      country: Scotland
                    - formatted_address:
                      - Corgi Homeheat Ltd
                      - 1 Masterton Park
                      - South Castle Drive
                      - Dunfermline
                      - Fife
                      thoroughfare: South Castle Drive
                      building_name: Masterton Park
                      sub_building_name: Corgi Homeheat Ltd
                      sub_building_number: ''
                      building_number: '1'
                      line_1: Corgi Homeheat Ltd
                      line_2: 1 Masterton Park
                      line_3: South Castle Drive
                      line_4: ''
                      locality: ''
                      town_or_city: Dunfermline
                      county: Fife
                      district: Fife
                      country: Scotland
                    - formatted_address:
                      - Corgi Homeplan
                      - 1 Masterton Park
                      - South Castle Drive
                      - Dunfermline
                      - Fife
                      thoroughfare: South Castle Drive
                      building_name: Masterton Park
                      sub_building_name: Corgi Homeplan
                      sub_building_number: ''
                      building_number: '1'
                      line_1: Corgi Homeplan
                      line_2: 1 Masterton Park
                      line_3: South Castle Drive
                      line_4: ''
                      locality: ''
                      town_or_city: Dunfermline
                      county: Fife
                      district: Fife
                      country: Scotland
                    - formatted_address:
                      - George Wimpey East Scotland Ltd
                      - 1 Masterton Park
                      - South Castle Drive
                      - Dunfermline
                      - Fife
                      thoroughfare: South Castle Drive
                      building_name: Masterton Park
                      sub_building_name: George Wimpey East Scotland Ltd
                      sub_building_number: ''
                      building_number: '1'
                      line_1: George Wimpey East Scotland Ltd
                      line_2: 1 Masterton Park
                      line_3: South Castle Drive
                      line_4: ''
                      locality: ''
                      town_or_city: Dunfermline
                      county: Fife
                      district: Fife
                      country: Scotland
                    - formatted_address:
                      - Taylor Wimpey East Scotland
                      - 1 Masterton Park
                      - ''
                      - Dunfermline
                      - Fife
                      thoroughfare: Masterton Park
                      building_name: ''
                      sub_building_name: Taylor Wimpey East Scotland
                      sub_building_number: ''
                      building_number: '1'
                      line_1: Taylor Wimpey East Scotland
                      line_2: 1 Masterton Park
                      line_3: ''
                      line_4: ''
                      locality: ''
                      town_or_city: Dunfermline
                      county: Fife
                      district: Fife
                      country: Scotland
                    - formatted_address:
                      - Trade Heating Services Ltd
                      - 1 Masterton Park
                      - South Castle Drive
                      - Dunfermline
                      - Fife
                      thoroughfare: South Castle Drive
                      building_name: Masterton Park
                      sub_building_name: Trade Heating Services Ltd
                      sub_building_number: ''
                      building_number: '1'
                      line_1: Trade Heating Services Ltd
                      line_2: 1 Masterton Park
                      line_3: South Castle Drive
                      line_4: ''
                      locality: ''
                      town_or_city: Dunfermline
                      county: Fife
                      district: Fife
                      country: Scotland
                    - formatted_address:
                      - Veolia
                      - 1 Masterton Park
                      - South Castle Drive
                      - Dunfermline
                      - Fife
                      thoroughfare: South Castle Drive
                      building_name: Masterton Park
                      sub_building_name: Veolia
                      sub_building_number: ''
                      building_number: '1'
                      line_1: Veolia
                      line_2: 1 Masterton Park
                      line_3: South Castle Drive
                      line_4: ''
                      locality: ''
                      town_or_city: Dunfermline
                      county: Fife
                      district: Fife
                      country: Scotland
        "400":
          description: Bad Request
        "401":
          description: "Unauthorized: Your admin key cannot be used for this resource"
        "403":
          description: Forbidden
        "404":
          description: NotFound
        "429":
          description: Too many requests
components:
  schemas:
    FindResponse:
      type: object
      properties:
        postcode: 
          type: string
        latitude: 
          type: number
        longitude: 
          type: number
        addresses:
          type: array
          formatted_address: 
            type: array
          thoroughfare: 
            type: string
          building_name: 
            type: string
          sub_building_name:
            type: string
          sub_building_number: 
            type: string
          building_number: 
            type: string
          line_1: 
            type: string
          line_2: 
            type: string
          line_3: 
            type: string
          line_4: 
            type: string
          locality: 
            type: string
          town_or_city: 
            type: string
          county: 
            type: string
          district: 
            type: string
          country: 
            type: string
          residential: 
            type: boolean